# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Sat Apr 19 01:18:13 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MirrorFoldDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MirrorFoldDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("dialog")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.mirror_dist = wx.SpinCtrl(self, wx.ID_ANY, "50", min=-1000, max=10000)
        self.mirror_dist.SetMinSize((200, 34))
        sizer_1.Add(self.mirror_dist, 0, 0, 0)

        self.mirror_dir = wx.Choice(self, wx.ID_ANY, choices=["horizontal", "vertical"])
        self.mirror_dir.SetMinSize((200, 34))
        self.mirror_dir.SetSelection(0)
        sizer_1.Add(self.mirror_dir, 0, 0, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()
        # end wxGlade

# end of class MirrorFoldDialog
